# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
sys.path.append("./back-end")
sys.path.append("./front-end")
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from tkinter import filedialog
import cv2
import client_mng
import msg
from tkinter import Tk
from editline import *

class Widget_1(QDialog):
    def __init__(self, parent=None):
        super(Widget_1, self).__init__(parent)
        self.ui_1 = Ui_Dialog_1()
        self.ui_1.setupUi_1(self)
        self.ui_1.loadbtn.clicked.connect(self.create)
        self.name = ""
        self.old_name = ""
    def create(self):
        self.name =  self.ui_1.line.text()
        if self.name == "":
                msg.ShowMsg("Info","Please check again!")
        else:
                client_mng.editName(self.old_name, self.name)
                self.close()
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(838, 534)
        self.photo = QtWidgets.QLabel(Form)
        self.photo.setGeometry(QtCore.QRect(5, 0, 491, 531))
        self.photo.setStyleSheet("border: 2px solid black;\n""image: url(./Img/Icon/Unknown_person.jpg);")
        self.photo.setText("")
        self.photo.setObjectName("photo")
        self.add_photo = QtWidgets.QPushButton(Form)
        self.add_photo.setGeometry(QtCore.QRect(530, 300, 271, 41))
        self.add_photo.setStyleSheet("background-color: gray;\n"
"border-radius: 10px;\n"
"border: 1px solid black;\n"
"color: #fff;\n"
"font-size: 20px;")
        self.add_photo.setObjectName("edit_name")
        self.edit_photo = QtWidgets.QPushButton(Form)
        self.edit_photo.setGeometry(QtCore.QRect(530, 350, 271, 41))
        self.edit_photo.setStyleSheet("background-color: #05f26c;\n"
"border-radius: 10px;\n"
"border: 1px solid black;\n"
"color: #fff;\n"
"font-size: 20px;")
        self.edit_photo.setObjectName("edit_photo")
        self.input_name = QtWidgets.QLineEdit(Form)
        self.input_name.setGeometry(QtCore.QRect(510, 250, 311, 41))
        self.input_name.setStyleSheet("font-size: 18px;\n""font-weight:600")
        self.input_name.setText("")
        self.input_name.setObjectName("input_name")
        self.edit_name = QtWidgets.QPushButton(Form)
        self.edit_name.setGeometry(QtCore.QRect(530, 400, 271, 41))
        self.edit_name.setStyleSheet("background-color: purple;\n"
"border-radius: 10px;\n"
"border: 1px solid black;\n"
"color: #fff;\n"
"font-size: 20px;")
        self.edit_name.setObjectName("edit_name")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(510, 210, 191, 20))
        self.label_2.setStyleSheet("font-size: 18px;\n"
"font-weight: 600;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(510, 140, 311, 51))
        self.label_3.setStyleSheet("font-size: 18px;\n"
"font-weight: 600;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(570, 20, 201, 121))
        self.label_4.setStyleSheet("image: url(Img/Icon/setting-worker.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.close_btn = QtWidgets.QPushButton(Form)
        self.close_btn.setGeometry(QtCore.QRect(530, 450, 271, 41))
        self.close_btn.setStyleSheet("background-color: red;\n"
"border-radius: 10px;\n"
"border: 1px solid black;\n"
"color: #fff;\n"
"font-size: 20px;")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.close_btn.setObjectName("close_btn")
        self.add_photo.clicked.connect(self.addImage)
        self.edit_photo.clicked.connect(self.editPhoto)
        self.edit_name.clicked.connect(self.editName)
        self.input_employ = ""
        self.file_path = ""
        self.new_name = ""
        self.ui_1 = Widget_1()

    def addImage(self):
        root = Tk()
        self.file_path = filedialog.askopenfilename(title="Chọn ảnh", filetypes=(("JPEG files", "*.jpg"), ("PNG files", "*.png"), ("All files", "*.*")))
        root.destroy()
        if self.file_path == "":
                return
        img = cv2.imread(self.file_path)
        Image = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        ConvertToQTFormat = QImage(Image.data, Image.shape[1], Image.shape[0], QImage.Format_RGB888)
        Pic = ConvertToQTFormat.scaled(591, 531)
        self.photo.setPixmap(QPixmap.fromImage(Pic))

    def editPhoto(self):
        self.input_employ = self.input_name.text()
        if self.input_employ == "" or self.file_path=="":
                msg.ShowMsg("Info","Please check again!")
                return 
        else:
                #input_employ = input_employ.replace(" ","_")
                self.UpdateInfo(self.input_employ, client_mng.CMD.EDITPHOTO)
                
    def editName(self):
        self.input_employ = self.input_name.text()
        if self.input_employ == "":
                msg.ShowMsg("Info","Please check again!")
                return 
        else:
                self.ui_1.old_name = self.input_employ
                self.ui_1.show()

    def UpdateInfo(self, input_employ, request):
        if request == client_mng.CMD.EDITPHOTO:
                client_mng.editPhoto(self.file_path, input_employ)
        elif request == client_mng.CMD.EDITNAME:
                client_mng.editName(input_employ, self.new_name)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.add_photo.setText(_translate("Form", "Add Photo"))
        self.edit_name.setText(_translate("Form", "Edit Name"))
        self.edit_photo.setText(_translate("Form", "Edit photo"))
        self.label_2.setText(_translate("Form", "Employee Name"))
        self.label_3.setText(_translate("Form", "Update Employee Information"))
        self.close_btn.setText(_translate("Form", "Close"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
