# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_Form_4(object):
    def setupUi_4(self, Form):
        Form.setObjectName("Form")
        Form.resize(559, 555)
        self.close_btn = QtWidgets.QPushButton(Form)
        self.close_btn.setGeometry(QtCore.QRect(420, 500, 111, 41))
        self.close_btn.setStyleSheet("font-size: 18px;\n"
"background-color: red;\n"
"color: white;")
        self.close_btn.setObjectName("close_btn")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(10, 50, 541, 431))
        self.listWidget.setStyleSheet("border: 1px solid black;")
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 10, 201, 31))
        self.label.setStyleSheet("font-size: 24px;\n"
"font-weight: 600;")
        self.label.setObjectName("label")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Employee List"))
        Form.setWindowIcon(QIcon("./Img/Icon/checklist.png"))
        self.close_btn.setText(_translate("Form", "CANCEL"))
        self.label.setText(_translate("Form", "WORKERS LIST"))

